#!/bin/sh
set -e

NAME=lddmodules
case "$1" in
    start)
        echo "loading mods"
        scull_load
        module_load faulty
        modprobe hello
        modprobe aesdchar
    ;;
    stop)
        echo "unloading mods"
        scull_unload
        module_unload faulty
        rmmod hello
        rmmod aesdchar
    ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit 0